# config.py - Configuración OPTIMIZADA y compatible con ASIO

# === MODOS DE OPERACIÓN ===
OPERATION_MODE = "dual"

# === CONFIGURACIÓN AUDIO BÁSICA ===
SAMPLE_RATE = 48000
BLOCKSIZE = 512
DTYPE = 'float32'
CHANNELS_MAX = 32
QUEUE_SIZE = 100  # ✅ Ya lo ajustaste bien - 580ms buffer
MAX_CLIENTS = 8

# === CONFIGURACIÓN WEB (Browser) ===
WEB_ENABLED = True
WEB_PORT = 5100
WEB_HOST = '0.0.0.0'
WEB_LATENCY_TARGET = 30
WEB_JITTER_BUFFER = 30
PING_INTERVAL = 5
PING_TIMEOUT = 10

# === CONFIGURACIÓN NATIVE (APK) ===
NATIVE_ENABLED = True
NATIVE_PORT = 5101
NATIVE_HOST = '0.0.0.0'
NATIVE_LATENCY_TARGET = 15
NATIVE_CHUNK_SIZE = 512
NATIVE_BUFFER_PACKETS = 3
NATIVE_PROTOCOL = 'TCP'
NATIVE_PRIORITY = 'realtime'
NATIVE_MAGIC_NUMBER = 0xA1D10A7C
NATIVE_PROTOCOL_VERSION = 2
NATIVE_HEADER_SIZE = 20
NATIVE_MAX_CLIENTS = 10
NATIVE_HEARTBEAT_INTERVAL = 2.0

# === DEBUG ===
VERBOSE = True
LOG_NATIVE_PACKETS = False
MEASURE_LATENCY = True
LOG_BUFFER_STATS = True

# === CONFIGURACIÓN WEBRTC (opcional) ===
WEBRTC_ENABLED = False
WEBRTC_AUDIO_CODEC = 'opus'
OPUS_BITRATE = 96000
OPUS_COMPLEXITY = 10
OPUS_FRAME_DURATION = 20
OPUS_PACKET_LOSS_PERC = 10

STUN_SERVERS = [
    'stun:stun.l.google.com:19302',
    'stun:stun1.l.google.com:19302',
    'stun:stun2.l.google.com:19302'
]

DATA_CHANNEL_PROTOCOL = 'audio-monitor-v1'
MAX_PACKET_SIZE = 1200
USE_DTX = False
USE_FEC = True

# === CONFIGURACIÓN PARA ESTABILIDAD ===

# Audio Capture
AUDIO_LATENCY = 'low'

# ✅ ASIO NO SOPORTA ESTAS FLAGS - Las dejamos como dict vacío
AUDIO_EXTRA_SETTINGS = {}

# Threading
USE_REALTIME_PRIORITY = True
AUDIO_THREAD_PRIORITY = 99

# Buffer Management
BUFFER_UNDERRUN_THRESHOLD = 0.2
BUFFER_OVERRUN_THRESHOLD = 0.9
BUFFER_STATS_INTERVAL = 5.0