# REDUCIDO PARA RF CRÍTICO
SAMPLE_RATE = 48000
BLOCKSIZE = 256          # 5.33ms ⭐ REDUCIDO PARA RF
QUEUE_SIZE = 2           # ⭐ MINIMO 2 BLOQUES PARA BUFFER PING-PONG (CORREGIDO)
WEB_PORT = 5100
WEB_HOST = '0.0.0.0'
NATIVE_PORT = 5101
NATIVE_HOST = '0.0.0.0'
NATIVE_MAX_CLIENTS = 5   # ⭐ REDUCIDO PARA LAN
VERBOSE = False
LOG_QUEUE_WARNINGS = False

# ⭐ NUEVO: PARÁMETROS RF
RF_MODE = True
RF_MAX_LATENCY_MS = 20   # ⭐ MÁXIMO 20ms LATENCIA
RF_DROP_OLD_MS = 30      # ⭐ DESCARTAR >30ms
RF_BUFFER_MS = 10        # ⭐ BUFFER MÍNIMO